/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.9
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.MVC.Interfaces;
using SitefinityWebApp.MVC.Models.ViewModels;
using System;

namespace SitefinityWebApp.Mvc.Models
{
	public class DemoWidgetModel : IResponsiveImageModel
	{
		public string Message { get; set; }
		public Guid DesktopImageId { get; set; }
		public Guid MobileImageId { get; set; }
		public string ImageProviderName { get; set; }
		public ResponsiveImageViewModel ResponsiveImageModel { get => new ResponsiveImageViewModel(this.DesktopImageId, this.MobileImageId, this.ImageProviderName);  }
	}
}