/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.9
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.Mvc.Models;
using System.ComponentModel;
using System.Web.Mvc;
using Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Controllers;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;
using Telerik.Sitefinity.Services;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "DemoWidget_MVC", Title = "Demo Widget", SectionName = "Demo Widgets")]
	public class DemoWidgetController : Controller, IPersonalizable
	{
        private string templateName = "DemoWidget";
        public string TemplateName
        {
            get
            {
                return this.templateName;
            }
            set
            {
                this.templateName = value;
            }
        }
        // GET: DemoWidget
        public ActionResult Index()
		{
			return View(TemplateName, Model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }
        private DemoWidgetModel model { get; set; }

        [TypeConverter(typeof(ExpandableObjectConverter))]
        public virtual DemoWidgetModel Model
        {
            get
            {
                if (this.model == null)
                {
                    this.model = ControllerModelFactory.GetModel<DemoWidgetModel>(base.GetType(), null);
                }
                return this.model;
            }
        }
    }
}